[general]
duration = 60
path = ["/home/othi/wallpaper/horizontal"]
path_vertical = ["/home/othi/wallpaper/vertical"]

[monitor."HDMI-A-1"]
resolution = "1920x1080"
transform = 90           # opt
vertical = true

[monitor."others"]
resolution = "1920x1080"
